# Generated by Django 6.0.5 on 2026-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaoAlvo',
            fields=[
                ('id_orgao_alvo', models.AutoField(db_column='id_orgao_alvo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao_orgao', max_length=45, null=True)),
                ('email_orgao', models.CharField(db_column='Email_orgao', max_length=100, null=True)),
                ('telefone', models.CharField(db_column='Telefone_orgao', max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Orgao Alvo',
                'verbose_name_plural': 'Orgaos Alvos',
                'db_table': 'orgao_alvo',
            },
        ),
    ]
