# Generated by Django 6.0.5 on 2026-06-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_seed_categorias'),
        ('orgao_alvo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgaoalvo',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', default=1, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
            preserve_default=False,
        ),
    ]
