# Generated by Django 6.0.5 on 2026-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=45, unique=True)),
                ('descricao_categoria', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
