# Generated by Django 6.0.5 on 2026-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, default='📍', max_length=10, null=True),
        ),
    ]
