# Generated by OpenClaude on 2026-06-16

from django.db import migrations, models


CATEGORY_COLORS = {
    'Iluminação': '#F8C146',
    'Abastecimento': '#3B82F6',
    'Infraestrutura': '#F97316',
    'Meio Ambiente': '#22C55E',
    'Transporte': '#8B5CF6',
    'Limpeza Urbana': '#8B4513',
}


def set_category_colors(apps, schema_editor):
    Categoria = apps.get_model('categoria', 'Categoria')
    for nome, cor in CATEGORY_COLORS.items():
        Categoria.objects.filter(nome_categoria=nome).update(cor=cor)


def reset_category_colors(apps, schema_editor):
    Categoria = apps.get_model('categoria', 'Categoria')
    Categoria.objects.filter(nome_categoria__in=CATEGORY_COLORS.keys()).update(cor='#F8C146')


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_seed_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(blank=True, default='#F8C146', max_length=7, null=True),
        ),
        migrations.RunPython(set_category_colors, reset_category_colors),
    ]
