# Generated by Django 6.0.5 on 2026-06-09 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('orgao_alvo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(db_column='id_denuncia', primary_key=True, serialize=False)),
                ('mensagem', models.CharField(db_column='Mensagem', max_length=255)),
                ('foto_video', models.CharField(db_column='Foto_video', max_length=100, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_column='Data_hora')),
                ('anonimo', models.BooleanField(db_column='Anonimo', default=False)),
                ('localizacao', models.CharField(db_column='Localizacao', max_length=100, null=True)),
                ('id_categoria', models.ForeignKey(db_column='CATEGORIA_id_categoria', on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('id_orgao_alvo', models.ForeignKey(db_column='ORGAO_ALVO_id_orgao_alvo', on_delete=django.db.models.deletion.CASCADE, to='orgao_alvo.orgaoalvo')),
                ('id_usuario', models.ForeignKey(db_column='USUARIO_id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'db_table': 'denuncia',
            },
        ),
    ]
