# Generated by Django 6.0.5 on 2026-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0002_alter_denuncia_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Em análise'), ('R', 'Resolvida')], db_column='Status', default='P', max_length=1),
        ),
    ]
