# Generated by Django for latitude/longitude fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_denuncia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='Latitude', decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='Longitude', decimal_places=6, max_digits=9, null=True),
        ),
    ]
