# Generated by Django 6.0.5 on 2026-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0006_denuncia_foto_video_2_denuncia_foto_video_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='foto_video',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='foto_video_2',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='foto_video_3',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='foto_1',
            field=models.ImageField(blank=True, db_column='Foto_1', null=True, upload_to='denuncias/'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='foto_2',
            field=models.ImageField(blank=True, db_column='Foto_2', null=True, upload_to='denuncias/'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='foto_3',
            field=models.ImageField(blank=True, db_column='Foto_3', null=True, upload_to='denuncias/'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='foto_4',
            field=models.ImageField(blank=True, db_column='Foto_4', null=True, upload_to='denuncias/'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='foto_5',
            field=models.ImageField(blank=True, db_column='Foto_5', null=True, upload_to='denuncias/'),
        ),
    ]
