# Generated by OpenClaude on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0007_remove_denuncia_foto_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta'), ('C', 'Crítica')], db_column='Prioridade', default='M', max_length=1),
        ),
    ]
