# Generated by Django 6.0.5 on 2026-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0008_denuncia_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='foto_1',
            field=models.ImageField(blank=True, db_column='Foto_1', max_length=500, null=True, upload_to='denuncias/'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='foto_2',
            field=models.ImageField(blank=True, db_column='Foto_2', max_length=500, null=True, upload_to='denuncias/'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='foto_3',
            field=models.ImageField(blank=True, db_column='Foto_3', max_length=500, null=True, upload_to='denuncias/'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='foto_4',
            field=models.ImageField(blank=True, db_column='Foto_4', max_length=500, null=True, upload_to='denuncias/'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='foto_5',
            field=models.ImageField(blank=True, db_column='Foto_5', max_length=500, null=True, upload_to='denuncias/'),
        ),
    ]
